---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-v2
automountServiceAccountToken: false

---
# API service version 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
  labels:
    app: api-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-v2
  template:
    metadata:
      labels:
        app: api-v2
        metrics: enabled
    spec:
      serviceAccountName: api-v2
      automountServiceAccountToken: true
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.20.0
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "127.0.0.1:9090"
        - name: "NAME"
          value: "api 2"
        - name: "MESSAGE"
          value: "Response from API Version 2"
